// 
// 
// 

package make_color

import "core:fmt"
import "core:os"
import "core:mem/virtual"
import "core:strings"
import "core:strconv"
import "core:path/filepath"

main :: proc() {
    if len(os.args) < 3 {
        fmt.eprintln("Program requires two path paramaters.")
        return
    }

    success, err_str := make_color(os.args[1], os.args[2])

    if (!success) {
        fmt.eprintfln("Error: %s", err_str)
    }
}

make_color :: proc(colortext_path, output_path : string) -> (bool, string) {
    Color_List :: struct {
        name: string,
        code: u32
    }

    arena : virtual.Arena
    alloc := virtual.arena_allocator(&arena)
    defer virtual.arena_destroy(&arena)

    context.allocator = alloc

    color_list: [dynamic]Color_List
    comment_list: [dynamic]string

    data, success := os.read_entire_file(colortext_path)

    if !success {
        return false, "Failed to read in color text file."
    }


    file_text := string(data)
    for line in strings.split_lines_iterator(&file_text) {
        if len(line) == 0 {
            continue
        }

        if strings.starts_with(line, "//") {
            append(&comment_list, strings.clone(line))
            continue
        }

        idx := strings.index(line, ": ")

        color_name := strings.to_ada_case(line[0:idx])

        idx += 1

        if len(line[idx:]) > 10 {
            // seek through to make sure we get the hex codes and nothing else
            fmt.printfln("%s - %d", color_name, len(line[idx:]))
        } else {
            hex, success := strconv.parse_uint(strings.trim_space(line[idx:]), 16)

            if !success {
                fmt.eprintfln("failed to parse %s as uint", line[idx:])
                continue
            }

            append(&color_list, Color_List {name = strings.clone(color_name), code = u32(hex) })
        }
    }

    fmt.printfln("%d", len(color_list))

    // Now we write the output
    b := strings.builder_make()
    w := strings.to_writer(&b)

    fmt.wprintfln(w, "// NOTE: This file is automatically generated\n// DO NOT EDIT see \"%s\" for details",
        filepath.base(colortext_path))

    for comment in comment_list {
        fmt.printfln("%s", comment)
        fmt.wprintfln(w, "%s", comment)
    }

    fmt.wprintfln(w, "package %s\n", filepath.short_stem(output_path))

    // write the enum
    fmt.wprintfln(w, "Color_Names :: enum {{")
    for color in color_list {
        fmt.wprintfln(w, "\t%s,", color.name)
    }
    fmt.wprintln(w, "}\n")

    fmt.wprintln(w, "RGBA_Color :: [4]f32\n")

    // write data:
    fmt.wprintfln(w, "Colors :: [Color_Names]RGBA_Color {{")
    for color in color_list {
        fmt.wprintfln(w, "\t.%s = {{%.6f, %.6f, %.6f, %.6f},", 
            color.name,
            f32((color.code >> 24) & 0xff) / 255.0,  // R
            f32((color.code >> 16) & 0xff) / 255.0,  // G
            f32((color.code >> 8)  & 0xff) / 255.0,  // B
            f32( color.code        & 0xff) / 255.0)  // A
    }
    fmt.wprintln(w, "}")

    s := strings.to_string(b)

    if !os.write_entire_file(output_path, transmute([]u8)s) {
        return false, "Failed to write output."
    }

    return true, ""
}
